import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

const aboutPath = new URL('../src/client/AboutSection.tsx', import.meta.url)
assert.equal(existsSync(aboutPath), true, '必须提供设置内的关于页面')

const client = readFileSync(new URL('../src/client/index.ts', import.meta.url), 'utf8')
const sidebar = readFileSync(new URL('../src/client/CodexSidebar.tsx', import.meta.url), 'utf8')
const host = readFileSync(new URL('../src/index.ts', import.meta.url), 'utf8')
const dependencies = readFileSync(new URL('../src/dependencies.ts', import.meta.url), 'utf8')
const about = readFileSync(aboutPath, 'utf8')
const locales = readFileSync(new URL('../src/client/locales.ts', import.meta.url), 'utf8')
const manager = readFileSync(new URL('../src/dependency-manager.ts', import.meta.url), 'utf8')

assert.match(client, /id: 'about'/, '关于页必须注册为最后的设置分区')
assert.match(client, /order: Number\.MAX_SAFE_INTEGER/, '关于页必须在注册排序中保持最后')
assert.match(dependencies, /@deepseek-ai\/dsh/, '关于页必须提供官方运行时手动升级')
assert.match(dependencies, /id: 'dsh'/, '关于页必须声明官方运行时依赖')
assert.doesNotMatch(dependencies, /id: 'suite'/, '不得再把套件作为关于页安装入口')
assert.match(dependencies, /@michengai\/dsh-codex-ui/, 'about must manage this plugin')
assert.match(dependencies, /id: 'ui'/, 'about must declare ui dependency id')
assert.match(dependencies, /@michengai\/dsh-agency-agents/, '关于页必须声明专家插件依赖')
assert.match(dependencies, /@michengai\/dsh-skills-manager/, '关于页必须声明技能插件依赖')
assert.match(dependencies, /@michengai\/dsh-archive-manager/, '关于页必须声明归档插件依赖')
assert.match(dependencies, /@michengai\/dsh-im-connect/, '关于页必须声明 IM 插件依赖')
assert.match(dependencies, /@michengai\/dsh-automation/, '关于页必须声明定时任务插件依赖')
assert.match(dependencies, /packageName: 'dshmarket'/, '关于页必须声明第三方插件市场依赖')
assert.match(dependencies, /id: 'im'/, 'about must declare im dependency id')
assert.match(dependencies, /id: 'schedule'/, 'about must declare schedule dependency id')
assert.match(dependencies, /id: 'market'/, 'about must declare market dependency id')
assert.match(host, /dependenciesEndpoint/, 'Host 必须提供依赖状态接口')
assert.match(host, /installDependency/, 'Host 必须提供受限的依赖安装操作')
assert.match(host, /get\('action'\) === 'progress'/, '依赖接口必须提供安装进度快照')
assert.match(host, /installProgressSnapshot/, '进度接口必须读取当前安装进度')
assert.match(host, /get\('action'\) === 'capabilities'/, '依赖接口必须提供无需访问 npm 的运行时能力查询')
assert.match(host, /officialTurnNavigator: await runtimeSupportsOfficialTurnNavigator/, '官方导航能力必须由实际 DSH 运行时版本决定')
assert.match(host, /updateAllDependencies/, 'Host 必须提供一次登记全部待更新插件的批量操作')
assert.match(host, /action.*update-all/, '依赖接口必须暴露一键更新操作')
assert.match(host, /restartAfterResponse/, '桌面热更新必须在依赖接口响应后再触发，避免浏览器请求被中断')
assert.match(host, /autoReload: typeof process\.send === 'function'/, '接口必须告诉页面当前宿主能否自动重载')
assert.match(manager, /process\.execPath/, '安装必须重新调用当前 DSH CLI，而不是直接启动 pnpm')
assert.match(manager, /PLUGIN_INSTALL_TIMEOUT_MS/, '安装子进程必须有超时上限')
assert.match(manager, /terminatePluginChild/, '安装超时或插件停用必须终止子进程')
assert.match(manager, /disposeDependencyInstaller/, '插件生命周期必须能清理遗留安装进程')
assert.match(host, /disposeDependencyInstaller\(\)/, 'Host effect 清理必须终止遗留安装进程')
assert.doesNotMatch(manager, /minimumReleaseAgeExclude/, '关于页不得维护 pnpm 发布时间保护白名单')
assert.match(manager, /applyRequiredBuildPolicies/, '单插件安装必须先写入 pnpm 构建脚本策略')
assert.match(manager, /protobufjs: false/, '单插件安装必须显式拒绝 protobufjs 的非必要 postinstall')
assert.match(manager, /koffi: false/, '单插件安装必须显式拒绝 koffi 的非必要 postinstall')
assert.doesNotMatch(manager, /ensureLatestReleaseAllowed/, '关于页安装与更新不得写入发布时间白名单')
assert.match(manager, /resolveDshCliEntry/, '必须把当前 CLI 入口收成绝对路径后再启动子进程')
assert.match(manager, /cwd: process\.cwd\(\)/, '子进程必须沿用当前 DSH 启动目录，而不是 dirname\(entry\)')
assert.match(manager, /pluginSpawnEnv/, '安装子进程必须补齐 pnpm 常见目录，而不是假设启动环境已有 PATH')
assert.match(manager, /PNPM_HOME/, 'PATH 补齐必须优先使用 PNPM_HOME')
assert.match(manager, /ensurePnpmEntry/, 'Web 中的 Desktop 桥接必须补上 pnpm 入口')
assert.match(manager, /DSH_PNPM_ENTRY/, '补齐的 pnpm 入口必须写入 DSH_PNPM_ENTRY')
assert.match(manager, /waitUntilPluginMounted/, 'Desktop 桥接写完 bundles 之前不得立刻判失败')
assert.match(manager, /runDshPlugin\(\['add'[\s\S]*recordDeclaredVersion/, 'Web 安装成功进入 bundles 后才允许把版本写进清单')
assert.match(manager, /desktopProfiles/, 'Desktop 必须通过 Host service 读取当前 profile')
assert.match(manager, /desktopPnpm/, 'Desktop 安装必须复用 Host 提供的包管理能力')
assert.doesNotMatch(manager, /desktopPnpmBootstrap/, '第三方插件不得读取 Desktop launcher 私有 bootstrap service')
assert.match(manager, /包管理服务尚未就绪/, 'Desktop 公开包管理服务缺失时必须失败，不得回退 ambient CLI')
assert.doesNotMatch(manager, /'--profile', 'web'/, '安装命令不得把目标 profile 硬编码为 web')
assert.match(manager, /runDshPlugin\(\['add', '--config\.minimumReleaseAge=0', \.\.\.batch\.map[\s\S]*--registry=https:\/\/registry\.npmjs\.org\//, '关于页批量安装必须单次关闭发布时间保护并走官方 npm 源')
assert.match(manager, /communityTargets[\s\S]*\[communityTargets\]/, '社区插件必须合并为一次安装，避免 Desktop 在批量过程中过早重启')
assert.match(manager, /pluginsToRemoveBeforeInstall/, '单独更新子插件前必须卸掉套件')
assert.doesNotMatch(manager, /发布时间保护拦截/, '关于页不得再向用户展示发布时间保护拦截')
assert.doesNotMatch(manager, /runPnpm|pnpm\.cmd/, '不得直接启动 Windows 的 pnpm.cmd')
assert.match(manager, /registry\.npmjs\.org/, '依赖状态必须从 npm registry 查询 latest 版本')
assert.match(manager, /DSH_RUNTIME_DIR/, '官方运行时版本必须读桌面运行目录')
assert.match(manager, /updateAvailable/, '依赖状态必须标记可更新的已安装插件')
assert.match(about, /data-installed=false\]\{color:var\(--dsw-alias-state-error-primary\)/, '未安装状态必须使用红色')
assert.match(about, /AbortController/, '关于页卸载必须中止进行中的依赖查询')
assert.match(about, /IntersectionObserver/, '进入关于页时必须重新查询依赖状态')
assert.match(about, /installingRef/, '关于页必须同步阻止并发安装')
assert.match(about, /action=progress/, '关于页安装中必须轮询进度')
assert.match(about, /dcu-about-progress/, '关于页安装中必须显示进度条')
assert.match(locales, /about\.progressHint/, '关于页必须提供安装进度提示文案')
assert.match(locales, /about\.installUnchanged/, '关于页必须说明命令成功但未进入 Profile 的失败')
assert.match(locales, /about\.packagesDone/, '关于页必须显示已完成包数量')
assert.match(about, /cache: 'no-store'/, '关于页必须绕过浏览器缓存重新查询')
assert.match(about, /stateRef/, '已有数据时再次进入不得整页打成加载中')
assert.match(about, /ref=\{root\}/, '关于页必须观察自身根节点而不是全局选择器')
assert.match(manager, /declared && input\.installedVersion/, '已安装必须同时看 profile 声明和磁盘版本')
assert.match(manager, /卸载后残留/, '卸载残留的 node_modules 不得继续标已安装')
assert.match(about, /alive\.current/, '关于页卸载后不得再写入安装状态')
assert.match(about, /data-installed=true\]\{color:var\(--dsw-alias-state-success-primary\)/, '已安装状态必须使用绿色')
assert.match(about, /MANAGED_DEPENDENCIES.some/, 'about must accept all managed dependency ids')
assert.match(about, /about\.update/, '关于页必须为落后版本提供更新操作')
assert.match(about, /about\.updateAll/, '关于页必须提供全部更新按钮')
assert.match(about, /action=update-all/, '全部更新必须调用批量接口，不能在浏览器逐项请求')
assert.match(about, /aria-busy/, '批量更新必须提供可访问的忙碌状态')
assert.match(about, /actionableCount > 0/, '存在未安装或可更新插件时必须显示顶部批量按钮')
assert.match(about, /payload\.autoReload === false \? t\('about\.restartManually'\) : t\('about\.restartRequired'\)/, 'Web 与 Desktop 必须显示各自真实的重载提示')
assert.match(locales, /about\.restartManually/, '独立 Web 安装后必须提示手动重启 DSH Web')
assert.match(manager, /updatableDependencyIds/, '批量操作必须选择未安装或可更新的插件')
assert.match(manager, /runtime\.desktopPnpm === undefined && requestHotUpdate\(\)/, '仅旧 Host 在登记完全部版本后请求一次热更新，Desktop 必须先执行宿主安装')
assert.match(about, /about\.feature\.search/, '关于页必须列出全局搜索能力')
assert.match(about, /about\.feature\.navigator/, '关于页必须列出会话轮次导航能力')
assert.match(sidebar, /selectSection\(t\('about\.nav'\)\)/, '缺失依赖的侧栏入口必须跳转关于页面')

assert.match(locales, /about\.dependency\.im/, '关于页必须提供 IM 插件名称')
assert.match(locales, /about\.dependency\.schedule/, '关于页必须提供定时任务插件名称')
assert.match(locales, /about\.dependency\.market/, '关于页必须提供插件市场名称')
assert.match(locales, /sidebar\.marketplace/, '插件入口必须认识市场分区标题')
