import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

const aboutPath = new URL('../src/client/AboutSection.tsx', import.meta.url)
assert.equal(existsSync(aboutPath), true, '必须提供设置内的关于页面')

const client = readFileSync(new URL('../src/client/index.ts', import.meta.url), 'utf8')
const sidebar = readFileSync(new URL('../src/client/CodexSidebar.tsx', import.meta.url), 'utf8')
const host = readFileSync(new URL('../src/index.ts', import.meta.url), 'utf8')
const dependencies = readFileSync(new URL('../src/dependencies.ts', import.meta.url), 'utf8')
const about = readFileSync(aboutPath, 'utf8')
const manager = readFileSync(new URL('../src/dependency-manager.ts', import.meta.url), 'utf8')

assert.match(client, /id: 'about'/, '关于页必须注册为最后的设置分区')
assert.match(client, /order: 100/, '关于页必须排在管理插件设置之后')
assert.match(dependencies, /@michengai\/dsh-codex-ui/, 'about must manage this plugin')
assert.match(dependencies, /id: 'ui'/, 'about must declare ui dependency id')
assert.match(dependencies, /@michengai\/dsh-agency-agents/, '关于页必须声明专家插件依赖')
assert.match(dependencies, /@michengai\/dsh-skills-manager/, '关于页必须声明技能插件依赖')
assert.match(dependencies, /@michengai\/dsh-archive-manager/, '关于页必须声明归档插件依赖')
assert.match(host, /dependenciesEndpoint/, 'Host 必须提供依赖状态接口')
assert.match(host, /installDependency/, 'Host 必须提供受限的依赖安装操作')
assert.match(manager, /process\.execPath/, '安装必须重新调用当前 DSH CLI，而不是直接启动 pnpm')
assert.match(manager, /minimumReleaseAgeExclude/, '用户确认更新的精确版本必须写入 Profile 发布时间白名单')
assert.match(manager, /ensureLatestReleaseAllowed/, '安装与更新前必须持久化本次确认的版本白名单')
assert.match(manager, /resolveDshCliEntry/, '必须把当前 CLI 入口收成绝对路径后再启动子进程')
assert.match(manager, /cwd: process\.cwd\(\)/, '子进程必须沿用当前 DSH 启动目录，而不是 dirname\(entry\)')
assert.match(manager, /\['add', `\$\{dependency\.packageName\}@\$\{latestVersion\}`\]/, '安装与更新必须通过 dsh plugin add 写入用户确认的精确版本')
assert.doesNotMatch(manager, /--config\.minimumReleaseAge=0/, '不得临时关闭整次 pnpm 解析的发布时间保护')
assert.doesNotMatch(manager, /runPnpm|pnpm\.cmd/, '不得直接启动 Windows 的 pnpm.cmd')
assert.match(manager, /registry\.npmjs\.org/, '依赖状态必须从 npm registry 查询 latest 版本')
assert.match(manager, /updateAvailable/, '依赖状态必须标记可更新的已安装插件')
assert.match(about, /data-installed=false\]\{color:var\(--dsw-alias-state-error-primary\)/, '未安装状态必须使用红色')
assert.match(about, /data-installed=true\]\{color:var\(--dsw-alias-state-success-primary\)/, '已安装状态必须使用绿色')
assert.match(about, /MANAGED_DEPENDENCIES.some/, 'about must accept all managed dependency ids')
assert.match(about, /about\.update/, '关于页必须为落后版本提供更新操作')
assert.match(about, /about\.feature\.search/, '关于页必须列出全局搜索能力')
assert.match(about, /about\.feature\.navigator/, '关于页必须列出会话轮次导航能力')
assert.match(sidebar, /selectSection\(t\('about\.nav'\)\)/, '缺失依赖的侧栏入口必须跳转关于页面')