import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { tickMarkSize } from '../src/client/TurnNavigator.tsx'

const sidebar = readFileSync(new URL('../src/client/CodexSidebar.tsx', import.meta.url), 'utf8')
const navigator = readFileSync(new URL('../src/client/TurnNavigator.tsx', import.meta.url), 'utf8')
const client = readFileSync(new URL('../src/client/index.ts', import.meta.url), 'utf8')

assert.match(sidebar, /--dsh-chat-content-width:800px/, '会话内容列必须使用更宽的 Codex 阅读宽度')
assert.match(sidebar, /\[data-composer-card\]\{min-height:96px/, '空输入卡片高度必须介于过矮和过高之间')
assert.match(sidebar, /\[data-input-mirror\]\{min-height:44px/, '空输入镜像高度必须接近 Codex 单行区')
assert.match(client, /conversation\.session\.header\.utilities/, '轮次导航必须挂在原生会话扩展位')
assert.doesNotMatch(client, /shell\.overlay/, '展开按钮不得再覆盖到会话标题上')
assert.match(navigator, /conversationAnchor/, '轮次跳转必须使用集中管理的 DSH 聊天锚点适配层')
assert.match(navigator, /turns\.label/, '轮次导航必须有无障碍名称')
assert.match(navigator, /focus-visible/, '轮次导航必须支持键盘聚焦展开')
assert.match(navigator, /prefers-reduced-motion/, '轮次跳转必须遵循减少动态效果设置')
assert.match(navigator, /top:50%;left:var\(--dcu-turn-left,288px\).*transform:translateY\(-50%\)/, '轮次刻度必须在侧栏右侧、会话左侧')
assert.match(navigator, /ResizeObserver/, '侧栏宽度变化时轮次导航必须重新定位')
assert.match(navigator, /getBoundingClientRect\(\)\.right\) \+ 16/, '轮次刻度必须贴在侧栏右缘外侧 16px')
assert.match(navigator, /left:16px/, '悬停气泡必须出现在刻度右边')
assert.doesNotMatch(navigator, /--dcu-turn-right/, '轮次刻度不得再放到会话右侧')
assert.match(navigator, /width:max-content/, '悬停气泡必须贴合文字宽度')
assert.match(navigator, /\.dcu-turn-summary\{[^}]*height:32px/, '悬停气泡高度必须是 Codex 的 32px 胶囊')
assert.match(navigator, /\.dcu-turn-summary\{position:absolute/, '悬停摘要必须是独立胶囊，刻度不得拉成白条')
assert.doesNotMatch(navigator, /\.dcu-turn-link:hover,.dcu-turn-link:focus-visible\{height:32px/, '悬停不得把刻度行拉高成白条')
assert.match(navigator, /width:16px;height:8px/, '轮次导航命中区必须紧凑')
assert.match(navigator, /--dcu-tick-w,5px/, '轮次导航默认必须是更短的微刻度')
assert.match(navigator, /\.dcu-turn-list\{display:grid;gap:2px/, '刻度默认间距必须收紧')
assert.match(sidebar, /\.dcu-compact\{width:100%/, '折叠窄轨必须填满宿主 56px 列，避免图标量到错误位置')
assert.match(sidebar, /BrandWordmark size=\{24\}/, '侧栏品牌标识必须放大')
assert.match(sidebar, /\.dcu-head-actions\{display:grid;grid-auto-flow:column;grid-auto-columns:28px;align-items:center;column-gap:8px;height:28px\}/, 'head actions grid')
assert.match(sidebar, /\.dcu-head\{display:grid;grid-template-columns:minmax\(0,1fr\) auto/, 'head single row')
assert.match(sidebar, /\.dcu-head\{[^}]*padding:8px 8px 8px 12px/, 'logo left inset')
assert.match(sidebar, /\.dcu-head \.dcu-icon\{display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px/, 'head icons aligned')
assert.match(sidebar, /<div className="dcu-head-actions"><button type="button" className="dcu-icon" aria-label=\{t\('sidebar\.collapse'\)\}[\s\S]*sidebar\.search/, '收缩按钮必须在 LOGO 右侧、搜索左侧，并随搜索一起靠右')
assert.match(sidebar, /const compact = collapsed \|\| width < 80/, '列宽小于 80px 时也必须进入窄轨')
assert.match(sidebar, /if \(compact\) return <aside className="dcu-root dcu-compact"/, '收缩后必须立刻切到窄轨，不得继续渲染文字菜单')
assert.match(sidebar, /dcu-compact-nav/, '窄轨必须渲染图标导航列')
assert.match(sidebar, /dcu-compact-nav[\s\S]*sidebar.newTask[\s\S]*sidebar.search[\s\S]*sidebar.experts[\s\S]*sidebar.skills[\s\S]*sidebar.plugins[\s\S]*sidebar.connectors[\s\S]*sidebar.schedule[\s\S]*sidebar.assistant/, '窄轨必须保留主导航图标')
assert.match(sidebar, /dcu-compact .dcu-settings-seat>button\{display:grid;place-items:center;width:36px;min-height:36px;padding:0!important;font-size:0!important/, '窄轨设置入口只能保留图标')
assert.match(sidebar, /dcu-compact" aria-label=\{t\('sidebar\.label'\)\}><style>\{stylesheet\}<\/style><button type="button" className="dcu-icon" aria-label=\{t\('sidebar\.expand'\)\} onClick=\{toggleSidebar\}><IconPanelLeftOutline16 size=\{16\} \/>/, '折叠态展开按钮必须位于窄轨顶部')
assert.match(sidebar, /background:#eef7f5/, '浅色侧栏必须使用 Codex 风格的浅青灰背景')
assert.match(sidebar, /body\[data-ds-dark-theme\] \.dcu-root\{background:#1c1f1e/, '暗色侧栏必须使用 Codex 风格的深灰绿背景')
assert.match(sidebar, /--dcu-sidebar-primary:#d1d5d3;--dcu-sidebar-secondary:#9ca39f;--dcu-sidebar-tertiary:#747b77;--dcu-sidebar-icon:#b2b8b5/, '暗色侧栏必须使用 Codex 风格的柔和文字层级，不能沿用宿主纯白文字')
assert.match(sidebar, /\.dcu-menu button[^}]*font-weight:500/, '主导航必须使用 Codex 风格的中等字重')
assert.match(sidebar, /\.dcu-extension-items button\{[^}]*font-size:13px;font-weight:400/, '扩展二级导航必须比父级更淡更小，形成缩进层级')
assert.match(sidebar, /\.dcu-im-tabs\{[^}]*border-bottom:1px solid var\(--dcu-sidebar-border\)/, '任务频道定时页签必须是整行切换器')
assert.match(sidebar, /\.dcu-im-tab\[data-on=true\]\{[^}]*font-weight:600/, '选中页签必须比未选项更重')
assert.match(sidebar, /dcu-extension-items[\s\S]*MenuIcon><IconUserOutline16/, '扩展子项必须保留二级图标')
assert.match(sidebar, /dcu-workspaces-tabs/, '有页签时不得再保留动作区和页签之间的第二条分隔线')
assert.match(sidebar, /--dcu-font:Inter,ui-sans-serif,system-ui/, '侧栏必须使用 Codex 风格的系统无衬线字体栈')
assert.match(sidebar, /\.dcu-settings-seat>button[^}]*font:14px\/20px var\(--dcu-font\);font-weight:500/, '底部设置入口必须与主导航保持同一文字层级')

assert.match(client, /observeConversationHeader/, '会话顶栏必须把对话/轨迹页签挪到子代理右侧')
assert.deepEqual(tickMarkSize(2, null, true), { width: 5, height: 1 })
assert.deepEqual(tickMarkSize(2, null, false), { width: 5, height: 1 })
assert.ok(tickMarkSize(2, 2, true).width > 14, '悬停当前条必须明显拉长')
assert.ok(tickMarkSize(3, 2, false).width > tickMarkSize(5, 2, false).width, '邻近刻度必须比远处更长')
assert.ok(tickMarkSize(2, 5, true).width < 8, '悬停其他条时，原来的选中刻度必须收回去')
assert.match(navigator, /data-hovering/, '轨道悬停时必须进入仅高亮悬停条的状态')
assert.match(navigator, /\[data-hovering=true\] \.dcu-turn-link\[aria-current=true\]/, '悬停时不得继续强调原来的选中刻度')
assert.match(navigator, /cubic-bezier\(\.16,1,\.3,1\)/, '刻度长短切换必须使用更丝滑的缓动')
