import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const sidebar = readFileSync(new URL('../src/client/CodexSidebar.tsx', import.meta.url), 'utf8')
const navigator = readFileSync(new URL('../src/client/TurnNavigator.tsx', import.meta.url), 'utf8')
const client = readFileSync(new URL('../src/client/index.ts', import.meta.url), 'utf8')

assert.match(sidebar, /--dsh-chat-content-width:800px/, '会话内容列必须使用更宽的 Codex 阅读宽度')
assert.match(sidebar, /\[data-composer-card\]\{min-height:142px/, '输入框必须提升最小高度')
assert.match(sidebar, /\[data-input-mirror\]\{min-height:78px/, '输入框必须保持自动增长的镜像高度机制')
assert.match(client, /conversation\.session\.header\.utilities/, '轮次导航必须挂在原生会话扩展位')
assert.match(navigator, /conversationAnchor/, '轮次跳转必须使用集中管理的 DSH 聊天锚点适配层')
assert.match(navigator, /turns\.label/, '轮次导航必须有无障碍名称')
assert.match(navigator, /focus-visible/, '轮次导航必须支持键盘聚焦展开')
assert.match(navigator, /prefers-reduced-motion/, '轮次跳转必须遵循减少动态效果设置')
assert.match(navigator, /top:50%;left:var\(--dcu-turn-left,288px\).*transform:translateY\(-50%\)/, '轮次导航必须在侧栏右缘的视口中部显示')
assert.match(navigator, /ResizeObserver/, '侧栏宽度变化时轮次导航必须重新定位')
assert.match(navigator, /getBoundingClientRect\(\)\.right\) \+ 16/, '轮次导航必须位于 Codex 窄侧栏右侧 16px')
assert.match(navigator, /height:32px/, '轮次导航悬停或聚焦后必须显著放大')
assert.match(navigator, /width:16px;height:8px/, '轮次导航轨道本身必须保持紧凑')
assert.match(navigator, /width:7px;height:1px/, '轮次导航默认必须是 Codex 风格的微刻度')
assert.match(navigator, /width:12px;flex-basis:12px;height:2px/, '当前轮次刻度只能略长于默认刻度')
assert.match(sidebar, /\.dcu-compact\{width:24px;min-width:24px/, '折叠侧栏必须收紧为 Codex 的 24px 窄轨')
assert.match(sidebar, /BrandWordmark size=\{24\}/, '侧栏品牌标识必须放大')
assert.match(sidebar, /background:#eef7f5/, '浅色侧栏必须使用 Codex 风格的浅青灰背景')
assert.match(sidebar, /body\[data-ds-dark-theme\] \.dcu-root\{background:#1c1f1e/, '暗色侧栏必须使用 Codex 风格的深灰绿背景')
assert.match(sidebar, /--dcu-sidebar-primary:#d1d5d3;--dcu-sidebar-secondary:#9ca39f;--dcu-sidebar-tertiary:#747b77;--dcu-sidebar-icon:#b2b8b5/, '暗色侧栏必须使用 Codex 风格的柔和文字层级，不能沿用宿主纯白文字')
assert.match(sidebar, /\.dcu-menu button[^}]*font-weight:500/, '主导航必须使用 Codex 风格的中等字重')
assert.match(sidebar, /\.dcu-extension-items button\{[^}]*font-size:14px;font-weight:400/, '扩展二级导航必须使用与主导航一致的字号和常规字重')
assert.match(sidebar, /--dcu-font:Inter,ui-sans-serif,system-ui/, '侧栏必须使用 Codex 风格的系统无衬线字体栈')
assert.match(sidebar, /\.dcu-settings-seat>button[^}]*font:14px\/20px var\(--dcu-font\);font-weight:500/, '底部设置入口必须与主导航保持同一文字层级')
