import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const tree = readFileSync(new URL('../src/client/session-tree.tsx', import.meta.url), 'utf8')
const channel = readFileSync(new URL('../src/client/ChannelBrowser.tsx', import.meta.url), 'utf8')
const schedule = readFileSync(new URL('../src/client/ScheduleBrowser.tsx', import.meta.url), 'utf8')
const workspace = readFileSync(new URL('../src/client/CodexWorkspaceBrowser.tsx', import.meta.url), 'utf8')
const sidebar = readFileSync(new URL('../src/client/CodexSidebar.tsx', import.meta.url), 'utf8')
const pending = readFileSync(new URL('../src/client/session-pending.ts', import.meta.url), 'utf8')
const locales = readFileSync(new URL('../src/client/locales.ts', import.meta.url), 'utf8')

assert.match(tree, /id: 'pin'[\s\S]*PinIcon/, '共用菜单置顶必须有图标')
assert.match(tree, /id: 'unread'[\s\S]*dcu-wb-unread/, '共用菜单未读必须有图标')
assert.match(tree, /id: 'fork'[\s\S]*IconBranchOutline16/, '共用菜单继续必须有图标')
assert.match(tree, /main-separator/, '共用菜单分隔必须与任务树一致')
assert.match(workspace, /sessionMenuItems\(t, \{ pinned:[\s\S]*includePath: true \}\)/, '任务树必须复用共用会话菜单')
assert.match(channel, /sessionMenuItems\(t, \{ pinned, unread \}\)/, '频道必须复用共用会话菜单')
assert.match(schedule, /sessionMenuItems\(t, \{ pinned, unread \}\)/, '定时必须复用共用会话菜单')
assert.match(channel, /<SessionRow /, '频道必须复用共用会话行')
assert.match(schedule, /<SessionRow /, '定时必须复用共用会话行')
assert.match(tree, /data-state="warning"[^]*dcu-wb-pending-label/, '共用会话行必须显示待处理交互警告状态和文本')
assert.match(workspace, /pendingInteractionForSession\(id, pendingInteractions, session\.pendingInteraction\)/, '任务树必须兼容 SessionSummary 和待处理交互 Store')
assert.match(channel, /pendingInteractionForSession\(id, pendingInteractions, sessions\.byId\[id\]\?\.pendingInteraction\)/, '频道必须兼容 SessionSummary 和待处理交互 Store')
assert.match(schedule, /pendingInteractionForSession\(id, pendingInteractions, sessions\.byId\[id\]\?\.pendingInteraction\)/, '定时必须兼容 SessionSummary 和待处理交互 Store')
for (const source of [workspace, channel, schedule]) {
  assert.match(source, /useSessionPendingInteraction \?\? useEmptySessionPendingInteraction/, '三棵树必须订阅宿主待处理交互 Store，并兼容旧宿主')
}
assert.match(sidebar, /<ChannelBrowser [^>]*useSessionPendingInteraction=\{useSessionPendingInteraction\}/, '侧栏必须向频道树透传待处理交互 Store')
assert.match(sidebar, /<ScheduleBrowser [^>]*useSessionPendingInteraction=\{useSessionPendingInteraction\}/, '侧栏必须向定时树透传待处理交互 Store')
assert.match(pending, /visiblePendingKind\(summaryKind\) \?\? visiblePendingKind\(pendingInteractions\.get\(sessionId\)\?\.kind\)/, '有效 SessionSummary 必须优先，缺失时回退待处理交互 Store')
assert.match(locales, /'sessions\.waitingAnswer': 'Waiting for answer'/, '等待回答英文文案必须与官方一致')
assert.match(locales, /'sessions\.waitingApproval': 'Waiting for approval'/, '等待审批英文文案必须与官方一致')
assert.match(locales, /'sessions\.planReview': 'Plan awaiting review'/, '计划待审英文文案必须与归档插件一致')
assert.match(channel, /<GroupHead /, '频道分组行必须走共用头部')
assert.doesNotMatch(channel, /showTip\(\{ title: group/, '频道项目行不得显示悬停卡片')
assert.doesNotMatch(schedule, /showTip\(\{ title: group/, '定时项目行不得显示悬停卡片')
assert.match(workspace, /showTip\(\{ kind: 'workspace'/, '任务项目文件夹悬停必须显示卡片')
assert.match(tree, /dcu-wb-tip-title/, '悬停卡片必须有标题行')
assert.doesNotMatch(tree, /dcu-wb-tip-title"><span className="dcu-wb-folder"><IconFolderClose16/, '会话卡片标题不得放文件夹图标：会话不是文件夹，且项目行已有同款图标')
assert.match(tree, /dcu-wb-tip-row"><span className="dcu-wb-folder"><IconFolderClose16/, '悬停卡片项目行必须带 Codex 官方收起文件夹图标')
assert.doesNotMatch(tree, /title=\{t\('sessions\.pinned'\)\}/, '会话行钉选标记不得写原生 title，避免浏览器 tips')
assert.doesNotMatch(tree, /title=\{t\(pinned \? 'sessions\.unpin' : 'sessions\.pin'\)\}/, '会话行钉选按钮不得写原生 title，避免浏览器 tips')
assert.doesNotMatch(tree, /title=\{t\('sessions\.archive'\)\}/, '会话行归档按钮不得写原生 title，避免浏览器 tips')
assert.doesNotMatch(workspace, /title=\{workspace\.path\}/, '项目标题不得写原生 title，路径已在悬停卡片展示')
assert.doesNotMatch(workspace, /title=\{t\('sessions\.pinned'\)\}/, '任务树会话行钉选标记不得写原生 title')
assert.doesNotMatch(workspace, /title=\{t\('sessions\.archive'\)\}/, '任务树会话行归档按钮不得写原生 title')
assert.match(tree, /draggable\?: boolean/, '共用会话行必须支持项目内排序')
assert.doesNotMatch(workspace, /pinSectionSessions|sectionSessionIds|pinSessionAt/, '置顶区只能接收项目，不能单独渲染会话')
