import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const tree = readFileSync(new URL('../src/client/session-tree.tsx', import.meta.url), 'utf8')
const channel = readFileSync(new URL('../src/client/ChannelBrowser.tsx', import.meta.url), 'utf8')
const schedule = readFileSync(new URL('../src/client/ScheduleBrowser.tsx', import.meta.url), 'utf8')
const workspace = readFileSync(new URL('../src/client/CodexWorkspaceBrowser.tsx', import.meta.url), 'utf8')
const sidebar = readFileSync(new URL('../src/client/CodexSidebar.tsx', import.meta.url), 'utf8')
const pending = readFileSync(new URL('../src/client/session-pending.ts', import.meta.url), 'utf8')
const sessionManager = readFileSync(new URL('../src/client/session-manager.ts', import.meta.url), 'utf8')
const locales = readFileSync(new URL('../src/client/locales.ts', import.meta.url), 'utf8')

assert.match(tree, /id: 'pin'[\s\S]*PinIcon/, '共用菜单置顶必须有图标')
assert.match(tree, /id: 'unread'[\s\S]*dcu-wb-unread/, '共用菜单未读必须有图标')
assert.match(tree, /id: 'fork'[\s\S]*IconBranchOutline16/, '共用菜单继续必须有图标')
assert.match(tree, /main-separator/, '共用菜单分隔必须与任务树一致')
assert.match(workspace, /sessionMenuItems\(t, \{ pinned:[\s\S]*includePath: true \}\)/, '任务树必须复用共用会话菜单')
assert.match(channel, /sessionMenuItems\(t, \{ pinned, unread \}\)/, '频道必须复用共用会话菜单')
assert.match(schedule, /sessionMenuItems\(t, \{ pinned, unread \}\)/, '定时必须复用共用会话菜单')
assert.match(channel, /<SessionRow /, '频道必须复用共用会话行')
assert.match(schedule, /<SessionRow /, '定时必须复用共用会话行')
assert.match(tree, /data-state="warning"[^]*dcu-wb-pending-label/, '共用会话行必须显示待处理交互警告状态和文本')
assert.match(workspace, /pendingInteractionForSession\(id, pendingInteractions, session\.pendingInteraction\)/, '任务树必须兼容 SessionSummary 和待处理交互 Store')
assert.match(channel, /pendingInteractionForSession\(id, pendingInteractions, sessions\.byId\[id\]\?\.pendingInteraction\)/, '频道必须兼容 SessionSummary 和待处理交互 Store')
assert.match(schedule, /pendingInteractionForSession\(id, pendingInteractions, sessions\.byId\[id\]\?\.pendingInteraction\)/, '定时必须兼容 SessionSummary 和待处理交互 Store')
for (const source of [workspace, channel, schedule]) {
  assert.match(source, /useSessionPendingInteraction \?\? useEmptySessionPendingInteraction/, '三棵树必须订阅宿主待处理交互 Store，并兼容旧宿主')
}
assert.match(sidebar, /<ChannelBrowser [^>]*useSessionPendingInteraction=\{useSessionPendingInteraction\}/, '侧栏必须向频道树透传待处理交互 Store')
assert.match(sidebar, /<ScheduleBrowser [^>]*useSessionPendingInteraction=\{useSessionPendingInteraction\}/, '侧栏必须向定时树透传待处理交互 Store')
assert.match(pending, /visiblePendingKind\(summaryKind\) \?\? visiblePendingKind\(pendingInteractions\.get\(sessionId\)\?\.kind\)/, '有效 SessionSummary 必须优先，缺失时回退待处理交互 Store')
assert.match(locales, /'sessions\.waitingAnswer': 'Waiting for answer'/, '等待回答英文文案必须与官方一致')
assert.match(locales, /'sessions\.waitingApproval': 'Waiting for approval'/, '等待审批英文文案必须与官方一致')
assert.match(locales, /'sessions\.planReview': 'Plan awaiting review'/, '计划待审英文文案必须与归档插件一致')
assert.match(channel, /<GroupHead /, '频道分组行必须走共用头部')
assert.doesNotMatch(channel, /showTip\(\{ title: group/, '频道项目行不得显示悬停卡片')
assert.doesNotMatch(schedule, /showTip\(\{ title: group/, '定时项目行不得显示悬停卡片')
assert.match(workspace, /showTip\(\{ kind: 'workspace'/, '任务项目文件夹悬停必须显示卡片')
assert.match(tree, /dcu-wb-tip-title/, '悬停卡片必须有标题行')
assert.doesNotMatch(tree, /dcu-wb-tip-title"><span className="dcu-wb-folder"><IconFolderClose16/, '会话卡片标题不得放文件夹图标：会话不是文件夹，且项目行已有同款图标')
assert.match(tree, /dcu-wb-tip-row"><span className="dcu-wb-folder"><IconFolderClose16/, '悬停卡片项目行必须带 Codex 官方收起文件夹图标')
assert.doesNotMatch(tree, /title=\{t\('sessions\.pinned'\)\}/, '会话行钉选标记不得写原生 title，避免浏览器 tips')
assert.doesNotMatch(tree, /title=\{t\(pinned \? 'sessions\.unpin' : 'sessions\.pin'\)\}/, '会话行钉选按钮不得写原生 title，避免浏览器 tips')
assert.doesNotMatch(tree, /title=\{t\('sessions\.archive'\)\}/, '会话行归档按钮不得写原生 title，避免浏览器 tips')
assert.doesNotMatch(workspace, /title=\{workspace\.path\}/, '项目标题不得写原生 title，路径已在悬停卡片展示')
assert.doesNotMatch(workspace, /title=\{t\('sessions\.pinned'\)\}/, '任务树会话行钉选标记不得写原生 title')
assert.doesNotMatch(workspace, /title=\{t\('sessions\.archive'\)\}/, '任务树会话行归档按钮不得写原生 title')
assert.match(tree, /draggable\?: boolean/, '共用会话行必须支持项目内排序')
assert.doesNotMatch(workspace, /pinSectionSessions|sectionSessionIds|pinSessionAt/, '置顶区只能接收项目，不能单独渲染会话')
assert.match(sidebar, /\.dcu-root\{[^}]*width:100%/, '侧栏根节点必须填满宿主网格列，不能露出宿主背景空带')
assert.doesNotMatch(workspace, /dcu-wb-project-current/, '项目文件夹不得保留当前会话的选中态')
assert.match(workspace, /\.dcu-wb\{--dcu-wb-inset:8px/, '工作区树必须使用 Codex 风格的 8px 横向留白')
assert.match(workspace, /\.dcu-wb-project-head\+\.dcu-wb-session,\.dcu-wb-project-head\+\.dcu-wb-nochat\{margin-top:4px\}/, '项目胶囊与首条会话之间必须保留层级间距')
assert.match(workspace, /\.dcu-wb-tree\{[^}]*overflow-x:hidden/, '工作区树不得因长标题出现横向滚动条')
assert.match(workspace, /\.dcu-wb-tree\{[^}]*padding-bottom:16px;scrollbar-gutter:auto/, '工作区树无滚动条时不得预留右侧滚动槽')
assert.match(workspace, /\.dcu-wb-section-label\{color:var\(--dcu-sidebar-secondary\);font:13px\/20px var\(--dcu-font,var\(--dsw-font-family\)\);font-weight:400;letter-spacing:0;padding-left:0\}/, '置顶、项目和最近必须使用比导航正文更克制的 13px 二级标题排版')
assert.match(workspace, /body\.animate\(\[from, to\], \{ duration: DISCLOSURE_EXIT_MS, easing: 'cubic-bezier\(\.16, 1, \.3, 1\)', fill: 'none' \}\)/, '展开收起必须使用宿主兼容的逐像素高度动画')
assert.match(workspace, /\.dcu-wb-section-label\{color:var\(--dcu-sidebar-secondary\);[^}]*padding-left:0\}/, '置顶、项目和最近必须与上方按钮的内容起点左对齐')
assert.match(workspace, /deleteWorkspaceGroup\(current, deleteGroupId\)[\s\S]*t\('workspace\.deleteGroupAction'\)/, '删除分组弹窗的确认按钮必须使用独立文案')
assert.match(locales, /'workspace\.deleteGroupAction': '删除分组'/, '中文删除分组确认文案必须准确')
assert.match(workspace, /const DISCLOSURE_EXIT_MS = 180/, '侧边栏展开与收起必须使用统一的 180ms 时长')
assert.match(workspace, /function DisclosureBody\(/, '顶层分区、项目和分组必须复用同一收起动画容器')
assert.match(workspace, /\.dcu-wb-section-body,\.dcu-wb-project-body,\.dcu-wb-collection-body\{display:block;min-height:0;height:auto;overflow:clip;opacity:1;transform:none/, '各层级内容必须保留原生动画所需的静态终态')
assert.doesNotMatch(workspace, /interpolate-size:allow-keywords/, '折叠容器不得混用 CSS auto 高度插值，避免与原生动画抢帧')
assert.match(workspace, /\.dcu-wb-section-body\[data-open=false\],\.dcu-wb-project-body\[data-open=false\],\.dcu-wb-collection-body\[data-open=false\]\{display:block;height:0;opacity:0;transform:translateY\(-2px\);pointer-events:none/, '各层级收起时必须保留在布局中完成统一的淡出与高度收缩动画')
assert.doesNotMatch(workspace, /\.dcu-wb-section-body>div::before/, '置顶、项目和最近等顶层分区不得绘制树线')
assert.match(workspace, /\.dcu-wb-collection-body\{padding-left:0\}/, '分组内项目胶囊不得因树层级缩进而变窄')
assert.match(workspace, /\.dcu-wb-collection-body \.dcu-wb-project-head\{padding-left:8px\}/, '分组内项目必须沿用标准胶囊内容留白')
assert.match(workspace, /\.dcu-wb-collection-body::before,\.dcu-wb-group-member::after\{display:none\}/, '分组内的白色树线与连接线必须隐藏')
assert.match(workspace, /\.dcu-wb-collection-head,\.dcu-wb-collection-head:focus-within\{background:color-mix\(in srgb,var\(--dcu-sidebar-hover\) 28%,transparent\)\}/, '分组文件夹必须使用很淡的常驻背景，键盘聚焦不得呈现选中态')
assert.match(workspace, /\.dcu-wb-collection-head:hover\{background:var\(--dcu-sidebar-hover\)\}/, '分组文件夹仅在鼠标悬停时增强背景反馈')
assert.match(workspace, /\.dcu-wb-collection-head\.dcu-wb-group-drop\{background:var\(--dcu-sidebar-hover\)\}/, '分组文件夹仅在项目拖放落点时显示背景')
assert.match(workspace, /\.dcu-wb-collections\{[^}]*min-width:0/, '分组网格必须允许长标题收缩')
assert.match(workspace, /\.dcu-wb-session\{[^}]*min-width:0;[^}]*overflow:hidden;[^}]*padding-right:28px/, '会话标题必须只为右侧状态图标预留宽度且可收缩')
assert.match(workspace, /\.dcu-wb-running\{position:absolute;right:10px;top:50%;[^}]*margin-top:-6px/, '运行指示器必须固定在会话行右侧')
assert.match(workspace, /\.dcu-wb-session:hover \.dcu-wb-running,[^}]*visibility:hidden/, '悬浮快捷操作出现时必须隐藏运行指示器，避免重叠')
assert.match(workspace, /completedBackgroundSessionIds\(previous, next, sessions\.current\)/, '后台会话结束时必须自动标为未读')
assert.match(sessionManager, /previous\[id\] === true && running !== true && id !== currentSessionId/, '当前打开会话结束时不得自动标未读')
