import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

const sidebar = readFileSync(new URL('../src/client/CodexSidebar.tsx', import.meta.url), 'utf8')
const client = readFileSync(new URL('../src/client/index.ts', import.meta.url), 'utf8')
const workspaceBrowser = readFileSync(new URL('../src/client/CodexWorkspaceBrowser.tsx', import.meta.url), 'utf8')
const settingsNavigation = readFileSync(new URL('../src/client/settings-navigation.ts', import.meta.url), 'utf8')
const visualSources = [
  sidebar,
  workspaceBrowser,
  readFileSync(new URL('../src/client/ConnectorsSection.tsx', import.meta.url), 'utf8'),
].join('\n')

assert.doesNotMatch(client, /SkillsSettingsSection|id: 'skills'/, '技能页必须由独立技能管理插件提供')
assert.match(client, /'connectors'/, '连接器必须注册为设置分区')
assert.doesNotMatch(client, /ArchivedSessionsSection|id: 'archived-sessions'/, '归档设置分区必须交由独立归档插件提供')
assert.equal(existsSync(new URL('../src/client/ArchivedSessionsSection.tsx', import.meta.url)), false, '本插件不得保留归档会话设置页面')
assert.match(sidebar, /sidebar\.newTask/, '侧栏必须显示新建任务')
assert.match(sidebar, /sidebar\.extensions/, '侧栏必须显示扩展管理分组')
assert.match(sidebar, /sidebar\.experts/, '扩展管理首项必须跳转专家插件')
assert.match(sidebar, /sidebar\.schedule/, '侧栏必须显示定时任务占位入口')
assert.match(sidebar, /sidebar\.assistant/, '侧栏必须显示个人助理入口')
assert.match(sidebar, /selectExternalSection\(t\('sidebar\.experts'\)/, '专家菜单必须直达外部专家插件')
assert.match(sidebar, /selectExternalSection\(t\('sidebar\.skills'\)/, '技能菜单必须直达外部技能插件')
assert.match(sidebar, /sidebar\.expertsInstallRequired/, '专家插件缺失时必须给出安装提示')
assert.match(sidebar, /sidebar\.skillsInstallRequired/, '技能插件缺失时必须给出安装提示')
assert.match(settingsNavigation, /onMissing\?\.\(\)/, '设置分区不存在时必须通知入口显示安装提示')
assert.match(sidebar, /selectSection\(t\('sidebar\.plugins'\)\)/, '插件菜单必须直达设置内的插件页')
assert.match(sidebar, /selectSection\(t\('sidebar\.connectors'\)\)/, '连接器菜单必须直达设置内的连接器页')
assert.doesNotMatch(sidebar, /settings:archives|archives\.title/, '全局搜索不得提供本插件的归档设置入口')
assert.doesNotMatch(sidebar, />归档会话<\/button>/, '底部不得保留独立归档会话按钮')
assert.match(sidebar, /openSettingsSection/, '设置跳转必须经过集中兼容层')
assert.match(sidebar, /\[role="dialog"\]\[aria-labelledby\]\{width:min\(1000px,calc\(100vw - 48px\)\);max-width:calc\(100vw - 48px\);height:min\(800px,calc\(100vh - 48px\)\)\}/, '设置窗口必须使用 1000px 宽度与 800px 高度，并保留视口边距')
assert.match(client, /'sidebar\.workspaces'/, '侧栏必须声明 DSH 工作区插槽')
assert.match(client, /'sidebar\.footer\.action'/, '侧栏必须声明 DSH footer action 插槽')
assert.match(sidebar, /renderSlot\('sidebar\.workspaces'/, '会话区域必须通过工作区插槽渲染')
assert.match(client, /priority: -1/, '自定义工作区树必须以更低优先级覆盖原生浏览器')
assert.match(workspaceBrowser, /workspace\.pinnedEmpty/, '置顶区域必须支持拖入项目')
assert.doesNotMatch(workspaceBrowser, /workspace\.recent/, '工作区树不得显示最近会话分区')
assert.match(workspaceBrowser, /insertWorkspaceBefore/, '工作区树必须保留项目拖拽排序')
assert.match(workspaceBrowser, /insertSessionBefore/, '工作区树必须保留会话拖拽排序')
assert.match(workspaceBrowser, /sessions\.export/, '会话菜单必须提供导出操作')
assert.match(workspaceBrowser, /archiveSession/, '会话菜单必须保留归档操作')
assert.match(workspaceBrowser, /deleteSession/, '会话菜单必须接入归档管理插件提供的永久删除服务')
assert.match(workspaceBrowser, /sessions\.delete/, '会话菜单必须提供删除会话操作')
assert.match(client, /remote\.workspaceRegistry/, '删除会话必须复用归档管理插件的远程服务')
assert.doesNotMatch(visualSources, /--dsw-alias-text-l[123]/, '不得使用宿主未提供的文字色令牌')
assert.match(visualSources, /--dcu-sidebar-primary/, '界面主文字必须使用侧栏自己的语义文字色')
assert.match(workspaceBrowser, /color:var\(--dcu-sidebar-primary\)/, '工作区树主文字必须继承侧栏的柔和主文字色')
assert.match(sidebar, /font:14px\//, '桌面侧栏基础字号必须达到 14px')
assert.match(sidebar, /place-items:center start/, '导航图标必须左对齐到设置图标列')
assert.match(sidebar, /padding:0 4px/, '导航图标必须左移至设置图标列')
assert.match(sidebar, /dcu-search-dialog/, '顶栏搜索必须打开全局搜索面板')
assert.doesNotMatch(workspaceBrowser, /dcu-wb-search/, '工作区区域不得保留重复搜索框')
assert.doesNotMatch(workspaceBrowser, /IconChevronRightOutline14/, '项目树不得保留展开箭头')
assert.match(workspaceBrowser, /toggleGroup\(workspace\.workspaceId\)/, '点击项目文件夹必须切换展开状态')
assert.match(workspaceBrowser, /IconFolderClose16/, '折叠项目必须使用关闭文件夹图标')
assert.match(workspaceBrowser, /isExpanded \? <IconFolderOpenOutline16[^]*IconFolderClose16/, '项目图标必须随展开状态切换')
assert.match(workspaceBrowser, /dcu-wb-project-current/, '当前会话所属项目必须显示选中态')
assert.match(workspaceBrowser, /deleteWorkspace/, '项目菜单必须接入 DSH 公开删除工作区服务')
assert.match(workspaceBrowser, /workspace\.delete/, '项目菜单必须提供删除工作区操作')
assert.match(workspaceBrowser, /padding-left:32px/, '会话标题必须与项目标题对齐')
assert.match(workspaceBrowser, /\.dcu-wb-section-label[^}]*font-size:12px;font-weight:500/, '工作区分组标签必须使用 Codex 风格的小号中等字重')
assert.match(workspaceBrowser, /\.dcu-wb-session-title\{[^}]*font-size:14px[^}]*font-weight:400/, '会话标题必须使用 14px 常规字重')
assert.match(workspaceBrowser, /\.dcu-wb-time\{[^}]*color:var\(--dcu-sidebar-secondary\)/, '会话时间必须使用 Codex 风格的柔和次级文字色')
assert.doesNotMatch(workspaceBrowser, /dcu-wb-status/, '工作区行不得将运行状态渲染为未读标记')
assert.match(workspaceBrowser, /unreadSessionIds\.includes\(id\) && <span className="dcu-wb-unread"/, '只有未读会话显示未读标记')
assert.match(workspaceBrowser, /session\.running \? <span className="dcu-wb-running"/, '运行会话必须在右侧显示状态圈')
assert.match(workspaceBrowser, /@keyframes dcu-wb-spin/, '运行状态圈必须使用旋转动画')
assert.doesNotMatch(workspaceBrowser, /isPinned && <span className="dcu-wb-pin"/, '项目置顶不应显示星标')
assert.match(workspaceBrowser, /dcu-wb-session-title[^]*dcu-wb-pin[^]*dcu-wb-time/, '置顶标识必须位于会话标题后、时间前')
assert.doesNotMatch(workspaceBrowser, /dcu-wb-pin"[^>]*>★<\//, '置顶会话不得再使用标题前的星标')
assert.doesNotMatch(workspaceBrowser, /IconFullscreenOutline16|openWindow|window\.open/, '桌面端嵌入前不得保留在新窗口打开功能')
assert.doesNotMatch(client, /as never|as unknown as/, '客户端插槽注册不得绕过官方类型')
