import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

const sidebar = readFileSync(new URL('../src/client/CodexSidebar.tsx', import.meta.url), 'utf8')
const client = readFileSync(new URL('../src/client/index.ts', import.meta.url), 'utf8')
const locales = readFileSync(new URL('../src/client/locales.ts', import.meta.url), 'utf8')
const workspaceBrowser = readFileSync(new URL('../src/client/CodexWorkspaceBrowser.tsx', import.meta.url), 'utf8')
const scheduleBrowser = readFileSync(new URL('../src/client/ScheduleBrowser.tsx', import.meta.url), 'utf8')
const scheduleSessions = readFileSync(new URL('../src/client/schedule-sessions.ts', import.meta.url), 'utf8')
const sessionRowActions = readFileSync(new URL('../src/client/session-row-actions.tsx', import.meta.url), 'utf8')
const hoverCard = readFileSync(new URL('../src/client/workspace-hover-card.tsx', import.meta.url), 'utf8')
const sessionTree = readFileSync(new URL('../src/client/session-tree.tsx', import.meta.url), 'utf8')
const settingsNavigation = readFileSync(new URL('../src/client/settings-navigation.ts', import.meta.url), 'utf8')
const automationTaskSettings = readFileSync(new URL('../src/client/automation-task-settings.ts', import.meta.url), 'utf8')
const connectors = readFileSync(new URL('../src/client/ConnectorsSection.tsx', import.meta.url), 'utf8')
const visualSources = [
  sidebar,
  workspaceBrowser,
  connectors,
].join('\n')

assert.doesNotMatch(client, /SkillsSettingsSection|id: 'skills'/, '技能页必须由独立技能管理插件提供')
assert.match(client, /'connectors'/, '连接器必须注册为设置分区')
assert.doesNotMatch(client, /ArchivedSessionsSection|id: 'archived-sessions'/, '归档设置分区必须交由独立归档插件提供')
assert.equal(existsSync(new URL('../src/client/ArchivedSessionsSection.tsx', import.meta.url)), false, '本插件不得保留归档会话设置页面')
assert.match(sidebar, /sidebar\.newTask/, '侧栏必须显示新建任务')
assert.match(sidebar, /sidebar\.extensions/, '侧栏必须显示扩展管理分组')
assert.match(sidebar, /sidebar\.experts/, '扩展管理首项必须跳转专家插件')
assert.match(sidebar, /sidebar\.schedule/, '侧栏必须显示定时任务入口')
assert.match(sidebar, /sidebar\.assistant/, '侧栏必须显示 IM 助理入口')
assert.match(sidebar, /selectExternalSection\(t\('sidebar\.experts'\)\)/, '专家菜单必须直达外部专家插件')
assert.match(sidebar, /selectExternalSection\(t\('sidebar\.skills'\)\)/, '技能菜单必须直达外部技能插件')
assert.match(sidebar, /selectExternalSection\(t\('sidebar\.experts'\)\)[^]*IconUserOutline16/, '专家菜单必须与设置中的专家图标一致')
assert.match(sidebar, /selectPluginSection\(\)[^]*IconPersonalizationOutline16/, '插件菜单必须与设置中的插件图标一致')
assert.match(sidebar, /selectExternalSection\(t\('sidebar\.schedule'\)\)/, '定时任务必须跳转设置中的定时任务分区')
assert.match(sidebar, /selectExternalSection\(\[t\('sidebar\.imSettings'\), 'IM助理'\]\)/, 'IM 助理必须同时匹配中英文设置分区标题')
assert.match(sidebar, /function ScheduleIcon/, '定时任务必须使用时钟图标')
assert.match(sidebar, /function ImAssistantIcon/, 'IM 助理必须使用聊天气泡图标')
assert.doesNotMatch(sidebar, /disabled title=\{t\('sidebar\.scheduleUnavailable'\)\}/, '定时任务不得再作为禁用占位')
assert.doesNotMatch(sidebar, /disabled title=\{t\('sidebar\.assistantUnavailable'\)\}/, 'IM 助理不得再作为禁用占位')
assert.doesNotMatch(sidebar, /IconGoalOutline16/, '定时任务不得再使用目标图标')
assert.doesNotMatch(sidebar, /IconAgentPresetOutline16/, 'IM 助理不得再使用 Agent 预设图标')
assert.doesNotMatch(sidebar, /selectSection\(t\('sidebar\.agentPresets'\)\)/, 'IM 助理不得跳转 Agent 预设设置页')
assert.match(sidebar, /selectSection\(t\('about\.nav'\)\)/, '依赖插件缺失时必须跳转关于页面')
assert.match(settingsNavigation, /onMissing\?\.\(\)/, '设置分区不存在时必须通知入口跳转关于页面')
assert.match(settingsNavigation, /pickSettingsSectionButton/, '设置跳转必须按优先标签选择分区')
assert.match(sidebar, /selectPluginSection\(\)/, '插件菜单必须按市场优先再回退原生插件管理')
assert.match(sidebar, /\[t\('sidebar.marketplace'\), t\('sidebar.plugins'\)\]/, '已安装第三方市场时优先打开插件市场')
assert.match(sidebar, /selectSection\(t\('sidebar\.connectors'\)\)/, '连接器菜单必须直达设置内的连接器页')
assert.match(sidebar, /\.dcu-root \.mcpConnectorLauncher,[^}]*display:none!important/, '第三方 MCP 连接器不得再保留独立侧栏入口')
assert.match(connectors, /const MCP_CONNECTOR_UI = '\/mcp-connector\/ui\/'/, '设置连接器页必须探测第三方插件的同源 UI')
assert.match(connectors, /fetch\(MCP_CONNECTOR_UI, \{ method: 'HEAD', cache: 'no-store'/, '第三方插件必须运行时探测，不能成为硬依赖')
assert.match(connectors, /marketAvailable[^]*ConnectorMarket[^]*NativeConnectorList/, '安装插件时必须显示市场，缺失时必须回退原生工具目录')
assert.match(connectors, /event\.origin !== window\.location\.origin[^]*event\.source !== frameWindow/, 'Prompt 消息桥接必须同时校验来源和 iframe 窗口')
assert.match(connectors, /mcp-connector:start-session-result/, 'Prompt 消息桥接必须向插件页面返回处理结果')
assert.match(client, /conversation\.input\.for\(binding\.ctx\)\.setDraft\(prompt\)/, '插件 Prompt 必须通过会话作用域输入机写入新会话草稿')
assert.match(client, /'conversation'\]/, '连接器 Prompt 桥接必须声明对话服务依赖')
assert.doesNotMatch(sidebar, /settings:archives|archives\.title/, '全局搜索不得提供本插件的归档设置入口')
assert.doesNotMatch(sidebar, />归档会话<\/button>/, '底部不得保留独立归档会话按钮')
assert.match(sidebar, /openSettingsSection/, '设置跳转必须经过集中兼容层')
assert.match(sidebar, /\[role="dialog"\]\[aria-labelledby\]\{width:min\(1000px,calc\(100vw - 48px\)\);max-width:calc\(100vw - 48px\);height:min\(800px,calc\(100vh - 48px\)\)\}/, '设置窗口必须使用 1000px 宽度与 800px 高度，并保留视口边距')
assert.match(client, /'sidebar\.workspaces'/, '侧栏必须声明 DSH 工作区插槽')
assert.match(client, /'sidebar\.footer\.action'/, '侧栏必须声明 DSH footer action 插槽')
assert.match(sidebar, /renderSlot\('sidebar\.workspaces'/, '会话区域必须通过工作区插槽渲染')
assert.match(client, /priority: -1/, '自定义工作区树必须以更低优先级覆盖原生浏览器')
assert.match(client, /openPathInHost/, '资源管理器动作必须直接调用 Host，不能经过可被第三方包装的 workspaces.openPath')
assert.doesNotMatch(client, /ctx\.workspaces\.openPath/, '资源管理器动作不得再进入侧边栏文件预览拦截链')
assert.match(workspaceBrowser, /const openPathImmediately[^]*setMenu\(undefined\)[^]*setHeaderMenu\(undefined\)[^]*run\('open-path'/, '资源管理器首次启动较慢时，菜单也必须在点击后立即收起')
assert.match(workspaceBrowser, /\.dcu-wb-rename-input\{[^}]*border:1px solid var\(--dsw-alias-border-l2\)[^}]*border-radius:8px/, '重命名输入框必须使用弹窗可见的全局边框 token 和矩形圆角')
assert.match(workspaceBrowser, /\.dcu-wb-rename-input:focus\{[^}]*var\(--dsw-alias-state-business-primary\)/, '重命名输入框必须提供清晰的蓝色焦点态')
assert.match(workspaceBrowser, /description=\{t\('sessions\.renameDescription'\)\}/, '项目和会话重命名弹窗必须显示辅助说明')
assert.match(sessionRowActions, /description=\{t\('sessions\.renameDescription'\)\}/, '频道和定时会话的重命名弹窗必须同步辅助说明')
assert.match(workspaceBrowser, /workspace\.pinnedEmpty/, '置顶区域必须支持拖入项目')
assert.match(workspaceBrowser, /if \(workspaces\.baselinesReady !== true\) return/, '工作区完整基线就绪前不得清理持久化置顶')
assert.match(workspaceBrowser, /prunePinnedWorkspaceIds/, '完整基线就绪后才可清理失效的置顶工作区')
assert.match(workspaceBrowser, /readHostPinnedWorkspaceIds/, '置顶必须从 Host Profile 恢复，不能只依赖当前端口的 localStorage')
assert.match(workspaceBrowser, /pinnedHostDirtyRef/, 'Host hydration 期间的用户操作必须优先，不能被迟到的读取覆盖')
assert.match(workspaceBrowser, /workspaceBaselineRef/, 'Host hydration 完成时必须按最新完整工作区基线清理失效置顶')
assert.match(workspaceBrowser, /PinIcon/, 'pin menu icon')
assert.doesNotMatch(workspaceBrowser, /IconGoalOutline16/, 'unpin must not use goal icon')
assert.match(workspaceBrowser, /dcu-wb-drop::before/, '拖放指示必须是 Codex 细插入线，而不是整块描边')
assert.match(workspaceBrowser, /radial-gradient\(circle at 4px 50%/, '插入线左侧必须有 Codex 小圆点')
assert.match(workspaceBrowser, /dcu-wb-drop-after/, '落在项目下半区必须把插入线画在整个项目组底部，不能插进标题与子会话之间')
assert.match(workspaceBrowser, /zone === 'pinned'/, '拖入置顶必须按最近插入位落点，不能落到最近分区')
assert.match(workspaceBrowser, /dcu-wb-pin-end/, '置顶末尾必须有独立落点，避免滑到项目或最近')
assert.match(workspaceBrowser, /\.dcu-wb-pin-start\.dcu-wb-drop::before,[^}]*\{top:0\}/, '置顶首个落点的插入线必须留在折叠容器内，不能被裁切')
assert.match(workspaceBrowser, /\.dcu-wb-project\.dcu-wb-drop::before,\.dcu-wb-session\.dcu-wb-drop::before\{top:0\}/, '项目组和会话插入线必须完整留在折叠容器内，不能裁掉圆点或蓝线')
assert.match(workspaceBrowser, /dcu-wb-drop-after::before[^}]*bottom:0/, '下方插入线也必须完整留在行内，不能被折叠容器裁切')
assert.doesNotMatch(workspaceBrowser, /\.dcu-wb-project-head\.dcu-wb-drop/, '项目排序蓝线不得挂在标题行上，否则会伪装成拖入子会话')
assert.match(workspaceBrowser, /className=\{`dcu-wb-project[^`]*dropsAfterLast/, '项目排序状态必须附着到整个项目组边界')
assert.match(workspaceBrowser, /const dropsAfterLast = zone === 'projects'/, '置顶末尾只能由 pin-end 画一条线，项目组不得重复绘制')
assert.match(workspaceBrowser, /pinDragActive && pinnedGroups\.length > 0 && <div className=\{`dcu-wb-pin-end/, '空置顶区只能保留一个语义相同的拖放目标')
assert.match(workspaceBrowser, /sessionDropTarget\?\.workspaceId === workspaceId && sessionDropTarget\.beforeId/, '会话蓝线必须使用与实际排序一致的 beforeId 锚点')
assert.match(workspaceBrowser, /workspaceDropTargetRef\.current = target/, 'dragover 必须同步记录最后一个项目落点，不能只等待 React state')
assert.match(workspaceBrowser, /const target = workspaceDropTargetRef\.current/, '置顶 drop 必须读取同步落点，确保蓝线位置松手后真正生效')
assert.doesNotMatch(workspaceBrowser, /box-shadow:inset 0 2px var\(--dsw-alias-state-business-primary\)/, '置顶拖放不得再使用内阴影蓝条')
assert.match(workspaceBrowser, /setDragImage/, 'custom drag image')
assert.match(workspaceBrowser, /\.dcu-wb-drag-ghost\{[^}]*opacity:0/, '拖拽预览不得覆盖置顶插入线')
assert.match(workspaceBrowser, /user-select:none/, 'no text selection during drag')
assert.match(workspaceBrowser, /workspace\.recent/, '工作区树必须显示未归组会话的最近分区')
assert.match(workspaceBrowser, /toggleSection\('pinned'\)/, '置顶分区必须可折叠')
assert.match(workspaceBrowser, /toggleSection\('projects'\)/, '项目分区必须可折叠')
assert.match(workspaceBrowser, /toggleSection\('recent'\)/, '最近分区必须可折叠')
assert.match(workspaceBrowser, /dcu-wb-section-caret/, '分区标题必须有 Codex 风格折叠箭头')
assert.match(workspaceBrowser, /section-head:hover .dcu-wb-section-caret/, '分区箭头必须仅在悬停该行时显示')
assert.match(workspaceBrowser, /dcu-wb-section-body\[data-open=false\]\{display:none\}/, '长列表分区不得动画 grid 或高度，避免每帧全树布局')
assert.doesNotMatch(workspaceBrowser, /transition:grid-template-rows/, '分区展开收缩不得使用高开销的布局动画')
assert.match(workspaceBrowser, /dcu-wb-section-caret svg/, '分区箭头必须使用居中的 SVG chevron')
assert.match(workspaceBrowser, /workspace\.recentEmpty/, '最近分区没有未归组会话时必须显示空态')
assert.match(workspaceBrowser, /workspace\.noChat/, '空项目展开后必须显示没有聊天')
assert.match(workspaceBrowser, /insertWorkspaceBefore/, '工作区树必须保留项目拖拽排序')
assert.match(workspaceBrowser, /insertSessionBefore/, '工作区树必须保留会话拖拽排序')
assert.doesNotMatch(workspaceBrowser, /exportSession|sessionExportFilename|sessions\.export/, '会话 ZIP 导出入口及实现必须移除')
assert.match(workspaceBrowser, /archiveSession/, '会话菜单必须保留归档操作')
assert.match(workspaceBrowser, /deleteSession/, '会话菜单必须接入归档管理插件提供的永久删除服务')
assert.match(workspaceBrowser, /sessions\.delete/, '会话菜单必须提供删除会话操作')
assert.match(sessionTree, /copyLink[^]*delete-separator[^]*sessions\.delete/, '删除会话必须位于菜单最底部的独立分隔栏')
assert.match(client, /remote\.workspaceRegistry/, '删除会话必须复用归档管理插件的远程服务')
assert.doesNotMatch(visualSources, /--dsw-alias-text-l[123]/, '不得使用宿主未提供的文字色令牌')
assert.match(visualSources, /--dcu-sidebar-primary/, '界面主文字必须使用侧栏自己的语义文字色')
assert.match(workspaceBrowser, /color:var\(--dcu-sidebar-primary\)/, '工作区树主文字必须继承侧栏的柔和主文字色')
assert.match(sidebar, /font:14px\//, '桌面侧栏基础字号必须达到 14px')
assert.match(sidebar, /place-items:center start/, '导航图标必须左对齐到设置图标列')
assert.match(sidebar, /padding:0 4px/, '导航图标必须左移至设置图标列')
assert.match(sidebar, /dcu-search-dialog/, '顶栏搜索必须打开全局搜索面板')
assert.doesNotMatch(workspaceBrowser, /dcu-wb-search/, '工作区区域不得保留重复搜索框')
assert.doesNotMatch(workspaceBrowser, /IconChevronRightOutline14/, '项目树不得保留展开箭头')
assert.match(workspaceBrowser, /toggleGroup\(expandKey, true\)/, '点击项目文件夹必须切换展开状态')
assert.match(workspaceBrowser, /IconFolderClose16/, '折叠项目必须使用官方收起文件夹图标')
assert.match(workspaceBrowser, /isExpanded \? <IconFolderOpenOutline16[^]*IconFolderClose16/, '项目图标必须随展开状态切换')
assert.match(workspaceBrowser, /dcu-wb-project-current/, '当前会话所属项目必须显示选中态')
assert.match(workspaceBrowser, /deleteWorkspace/, '项目菜单必须接入 DSH 公开删除工作区服务')
assert.match(workspaceBrowser, /workspace\.delete/, '项目菜单必须提供删除工作区操作')
assert.match(workspaceBrowser, /onContextMenu=\{\(event\) => \{ event\.preventDefault\(\); event\.stopPropagation\(\); dismissTip\(\); setMenu\(\{ id: workspace\.workspaceId, type: 'workspace', x: event\.clientX, y: event\.clientY \}\) \}\}/, '右键项目必须按鼠标位置打开菜单')
assert.match(workspaceBrowser, /onContextMenu=\{\(event\) => \{ event\.preventDefault\(\); event\.stopPropagation\(\); dismissTip\(\); setMenu\(\{ id, type: 'session', x: event\.clientX, y: event\.clientY \}\) \}\}/, '右键会话必须按鼠标位置打开菜单')
assert.match(workspaceBrowser, /pointerMenuRect/, '右键菜单必须用指针坐标做锚点')
assert.match(workspaceBrowser, /padding-left:28px/, '会话必须比项目多缩进一层，形成父子层级')
assert.match(workspaceBrowser, /\.dcu-wb-section-label[^}]*color:var\(--dcu-sidebar-tertiary\);font-size:13px;font-weight:400/, '置顶项目最近必须使用 Codex 的弱化灰阶与常规字重')
assert.match(workspaceBrowser, /\.dcu-wb-section\+\.dcu-wb-section\{margin-top:12px\}/, '置顶、项目和最近之间必须留出分区间距')
assert.match(workspaceBrowser, /\.dcu-wb-session-title\{[^}]*font-size:14px[^}]*font-weight:400/, '会话标题必须使用 Codex 的 14px')
assert.match(workspaceBrowser, /\.dcu-wb-project-title\{[^}]*font-size:14px[^}]*font-weight:400/, '项目标题必须使用 Codex 的常规字重，不能显得过黑')
assert.doesNotMatch(workspaceBrowser, /dcu-wb-time/, '会话行不得再显示时间')
assert.match(workspaceBrowser, /dcu-wb-tip/, '会话必须提供 Codex 风格悬停卡片')
assert.match(workspaceBrowser, /dcu-wb-tip-time/, '会话时间必须出现在悬停卡片右上角')
assert.match(workspaceBrowser, /formatHoverTime\(session.updatedAt\)/, '会话悬停必须使用紧凑相对时间')
assert.match(workspaceBrowser, /dcu-wb-project-head[^]*onMouseEnter=\{\(event\) => \{ const box = hoverCardAnchor/, '悬停项目行必须显示卡片')
assert.match(workspaceBrowser, /showTip\(\{ kind: 'workspace'/, '项目文件夹悬停必须显示卡片，供顶栏文件夹复用')
assert.match(hoverCard, /workspace\.edit/, '项目悬停必须提供编辑项目')
assert.doesNotMatch(workspaceBrowser, /dcu-wb-status/, '工作区行不得将运行状态渲染为未读标记')
assert.match(workspaceBrowser, /dcu-wb-session-title[^]*unreadSessionIds\.includes\(id\) \? <span className="dcu-wb-unread"[^]*session\.running/, '未读点必须位于标题右侧，并替代右侧时间状态')
assert.match(workspaceBrowser, /\.dcu-wb-unread\{[^}]*width:7px[^}]*margin-left:8px/, '未读点必须保持 Codex 风格的小尺寸并与标题留出间距')
assert.match(workspaceBrowser, /\.dcu-wb-session:hover \.dcu-wb-quick-actions/, '会话悬停时必须显示 Codex 风格的快捷操作')
assert.match(workspaceBrowser, /\.dcu-wb-project-head\{height:28px/, '项目行高度必须收紧，避免项目与首个会话间距过大')
assert.match(workspaceBrowser, /dcu-wb-project-head\+\.dcu-wb-session,\.dcu-wb-project-head\+\.dcu-wb-nochat\{margin-top:0\}/, '项目与首个会话或空态之间不得保留额外间距')
assert.match(workspaceBrowser, /\.dcu-wb-nochat\{padding:0 8px 4px 28px/, '空项目提示必须与普通会话使用相同的紧凑起始间距')
assert.match(workspaceBrowser, /dcu-wb-quick-actions"><button[^]*dcu-wb-quick-pin[^]*<svg[^]*IconArchiveOutline20/, '会话悬停快捷操作必须使用图钉与归档图标')
assert.match(workspaceBrowser, /\.dcu-wb-context-anchor\{opacity:0;pointer-events:none\}/, '右键菜单锚点必须隐藏三点图标')
assert.match(workspaceBrowser, /className="dcu-wb-more dcu-wb-context-anchor"/, '右键菜单必须使用隐藏的三点锚点')
assert.match(workspaceBrowser, /onContextMenu=\{\(event\) => \{ event\.preventDefault\(\); event\.stopPropagation\(\); dismissTip\(\); setMenu\(\{ id, type: 'session', x: event\.clientX, y: event\.clientY \}\) \}\}/, '右键会话必须按鼠标位置打开菜单')
assert.match(workspaceBrowser, /session\.running \? <span className="dcu-wb-running"/, '运行会话必须在右侧显示状态圈')
assert.match(workspaceBrowser, /@keyframes dcu-wb-spin/, '运行状态圈必须使用旋转动画')
assert.doesNotMatch(workspaceBrowser, /isPinned && <span className="dcu-wb-pin"/, '项目置顶不应显示星标')
assert.match(workspaceBrowser, /dcu-wb-session-title[^]*dcu-wb-pin/, '置顶标识必须位于会话标题后')
assert.doesNotMatch(workspaceBrowser, /dcu-wb-pin"[^>]*>★<\//, '置顶会话不得再使用标题前的星标')
assert.doesNotMatch(workspaceBrowser, /IconFullscreenOutline16|openWindow|window\.open/, '桌面端嵌入前不得保留在新窗口打开功能')
assert.doesNotMatch(client, /as never|as unknown as/, '客户端插槽注册不得绕过官方类型')

assert.match(sidebar, /showCompanionTabs/, '未安装配套插件时不得显示任务/频道/定时页签栏')
assert.match(sidebar, /showChannels && <button type="button" className="dcu-im-tab"/, '频道页签必须在 IM 插槽有注册后才显示')
assert.match(sidebar, /showSchedule && <button type="button" className="dcu-im-tab"/, '定时页签必须在定时插槽有注册后才显示')
assert.match(sidebar, /view: 'overview',[\s\S]*showViewSwitch: false/, '任务概览必须直接渲染卡片，不能嵌套第三层视图切换')
assert.match(sidebar, /\[data-slot="sidebar\.schedule"\][^}]*display:flex!important[^}]*width:100%/, '任务概览插槽必须撑满定时侧栏，不能按内容宽度收缩')
assert.match(sidebar, /\.dcu-expanded-shell\{[^}]*flex:1 1 0[^}]*overflow:hidden/, '长会话列表必须在侧栏内部滚动，不能把底部设置入口挤出视口')
assert.match(client, /companionSlots/, '侧栏必须注入配套插槽占用快照')
assert.match(sidebar, /\.dcu-native-workspaces\{flex-direction:column\}/, '工作区槽位必须纵向排列，避免第三方 Portal 入口把会话树挤成左右两列')
assert.match(sidebar, /\.dcu-native-workspaces>\[data-mcp-connector-top-mount=true\]\{flex:none\}/, 'MCP 连接器入口必须保持独立整行，不能占用会话树的弹性空间')

assert.match(sidebar, /shouldCollapseOnSidebarDrag/, '向左拖动侧栏超过阈值必须自动收缩')

assert.doesNotMatch(client, /observePermissionMenus|permission-i18n/, '权限菜单必须完全沿用官方样式')
assert.doesNotMatch(locales, /permission.read-only.title/, '官方已提供权限文案，插件不得重复维护')

assert.match(client, /observeSlimSidebar/, '展开侧栏必须收到接近 Codex 的列宽')
assert.match(client, /observeSettingsNavIcons/, '设置导航必须改用侧栏同款图标')

assert.match(client, /registrant: 'michengai-codex-ui'/, '侧栏注册必须带可识别的 Codex UI id，避免 IM 再包一层页签')
assert.match(sidebar, /ima-tabs/, '配套插件内层任务/频道页签必须隐藏')
assert.match(sidebar, /ChannelBrowser/, '频道必须用任务树同款组件接管，而不是渲染 IM 原生树')
assert.match(sidebar, /ScheduleBrowser/, '定时必须用任务树同款组件接管')
assert.match(sidebar, /ScheduleBrowser[\s\S]*overviewContent=\{scheduleOverviewSlot\}/, '任务概览必须作为定时页内的独立入口，不能替换原会话树')
assert.match(scheduleBrowser, /dcu-schedule-views[\s\S]*ScheduleBrowserTree[\s\S]*overviewContent/, '定时页内层 TAB 必须保留原 ScheduleBrowserTree，并在另一个面板展示任务卡片')
assert.match(scheduleBrowser, /onContextMenu/, '定时执行记录必须保留原右键菜单事件')
assert.match(scheduleSessions, /localeCompare\(right\.label, 'zh-CN'/, '定时执行记录文件夹必须按任务名稳定排序，归档会话时不得跳位')
assert.match(scheduleBrowser, /schedule\.taskSettings/, '执行记录文件夹菜单必须提供任务设置入口')
assert.match(scheduleBrowser, /schedule\.archiveGroup/, '执行记录文件夹菜单必须提供整组归档入口')
assert.match(scheduleBrowser, /setArchiveGroupTarget/, '整组归档必须先进入确认状态，不能点击菜单后直接执行')
assert.match(scheduleBrowser, /for \(const id of target\.sessionIds\) await archiveSession/, '确认后必须归档组内全部会话')
assert.match(sidebar, /openTaskSettings=\{\(request\) => \{[\s\S]*requestAutomationTaskSettings\(request\)/, '任务设置入口必须把目标任务传给定时任务设置页')
assert.match(automationTaskSettings, /sessionStorage\.setItem\(AUTOMATION_TASK_SETTINGS_STORAGE_KEY/, '具体任务设置请求必须跨设置页挂载保存一次')
assert.match(automationTaskSettings, /CustomEvent\(AUTOMATION_TASK_SETTINGS_EVENT/, '已挂载的定时任务设置页必须能即时收到目标任务')
assert.match(readFileSync(new URL('../src/client/ChannelBrowser.tsx', import.meta.url), 'utf8'), /onContextMenu/, '频道会话必须复用任务树右键菜单')
assert.match(sessionTree, /dcu-wb-quick-actions/, '频道会话必须复用任务树悬停按钮')

assert.match(workspaceBrowser, /dismissTip\(\); setMenu/, '右键打开菜单时必须立刻关闭悬停卡片')
assert.match(sessionTree, /id: 'pin'[\s\S]*PinIcon/, '频道右键置顶必须有图标')
assert.match(sessionTree, /id: 'fork'[\s\S]*IconBranchOutline16/, '定时右键继续必须有图标')
assert.doesNotMatch(workspaceBrowser, /standalonePinnedSessionIds|sectionSessionIds|pinSessionAt/, '置顶区只能置顶项目，不得维护独立会话列表')
assert.match(workspaceBrowser, /const pinDragActive = workspaceDragId !== undefined/, '置顶区只能在拖动项目时成为落点')
assert.match(workspaceBrowser, /isExpanded && shownIds.map/, '置顶项目必须和项目区一样可展开会话')
assert.doesNotMatch(workspaceBrowser, /onClick=\{\(\) => \{ if \(zone !== 'pinned'\) toggleGroup/, '置顶项目点击不得被拦截，必须能切换展开状态')
assert.doesNotMatch(workspaceBrowser, /zone !== 'pinned' && isExpanded \? <IconFolderOpenOutline16/, '置顶项目图标必须反映实际展开状态')
assert.match(workspaceBrowser, /pinnedGroups.map\(workspace => renderGroup\(workspace, 'pinned'\)\)/, '置顶区必须只渲染置顶项目文件夹')
assert.doesNotMatch(workspaceBrowser, /readSessionDrag\(event.dataTransfer/, '置顶落点不得读取或接收会话拖拽载荷')
assert.match(locales, /'workspace\.pinnedEmpty': '拖动项目到此处置顶'/, '置顶空态必须明确只接受项目')
