import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const browser = readFileSync(new URL('../src/client/CodexWorkspaceBrowser.tsx', import.meta.url), 'utf8')
const locales = readFileSync(new URL('../src/client/locales.ts', import.meta.url), 'utf8')

assert.match(browser, /workspaceGroups\.map\(renderWorkspaceCollection\)/, '项目区必须按集合标题渲染持久化分组')
assert.match(browser, /initialWorkspaceGroups = useMemo\(\(\) => readWorkspaceGroupsCache\(storage\(\)\), \[\]\)/, '分组首帧必须从浏览器同步缓存恢复')
assert.match(browser, /useState<WorkspaceGroup\[\]>\(\(\) => initialWorkspaceGroups\.workspaceGroups\)/, '分组状态必须使用同步缓存作为初始值')
assert.match(browser, /saveWorkspaceGroupsCache\(storage\(\), workspaceGroups, workspaceGroupsPendingHostSyncRef\.current\)/, '分组变化必须同步写入浏览器缓存')
assert.match(browser, /\.catch\(\(\) => \{[\s\S]{0,160}pinnedHostHydratedRef\.current = true/, 'Host 读取失败后不得永久阻断后续偏好写回')
assert.match(browser, /writeWorkspaceGroupDrag\(event\.dataTransfer, groupId, group\.title\)/, '分组标题必须写入独立的分组拖拽载荷')
assert.match(browser, /className=\{`dcu-wb-collection-head[^`]*`\} draggable/, '项目分组标题必须可以拖动')
assert.match(browser, /className="dcu-wb-collection-label" draggable aria-expanded=\{isExpanded\}/, '分组标题按钮本身必须可以启动 Chrome 原生拖拽')
assert.match(browser, /reorderDropBeforeId\(workspaceGroupIds, draggedGroupId, groupId,/, '分组拖动必须按标题上下半区计算精确落点')
assert.match(browser, /moveWorkspaceGroup\(current, draggedGroupId, beforeId\)/, '放下分组后必须更新持久化分组顺序')
assert.match(browser, /dcu-wb-group-order-drop/, '分组排序必须显示独立插入线反馈')
assert.doesNotMatch(browser, /dcu-wb-group-order-drop-after/, '分组末尾只能由未分组顶部显示一条插入线，不能重复绘制')
assert.match(browser, /current\.beforeId === target\.beforeId \? current : target/, '重复的分组拖拽落点不得触发重复渲染')
assert.match(browser, /className=\{`dcu-wb-ungrouped[^`]*`\} onDragOver=/, '未分组必须可以作为将自定义分组移到末尾的落点')
assert.doesNotMatch(browser, /<div className=\{`dcu-wb-ungrouped[^`]*`\} draggable/, '未分组是固定系统分类，不得作为拖拽源')
assert.doesNotMatch(browser, /className="dcu-wb-collection-label" draggable aria-expanded=\{ungroupedExpanded\}/, '未分组标题按钮不得作为拖拽源')
assert.match(browser, /const regularGroups = groups\.items\.filter\(workspace => !projectPinned\(workspace\.workspaceId\)\)/, '项目区不得重复渲染置顶项目')
assert.match(browser, /setPinnedWorkspaceIds\(ids => ids\.filter\(id => id !== dragged\)\)/, '从置顶投放到项目区时必须取消置顶')
assert.match(browser, /workspaceGroups\.length > 0 && renderUngroupedCollection\(\)/, '仅在已有分组时显示未分组小节')
assert.match(browser, /const ungroupedExpandKey = 'workspace-group:ungrouped'/, '未分组小节必须使用独立且稳定的折叠状态键')
assert.match(browser, /className=\{`dcu-wb-collection-head\$\{ungroupedDropActive/, '未分组必须复用二级分类标题样式')
assert.match(browser, /className="dcu-wb-collection-label" aria-expanded=\{ungroupedExpanded\}/, '未分组标题必须提供可访问的展开状态')
assert.match(browser, /toggleGroup\(ungroupedExpandKey, true\)/, '未分组标题必须支持展开和收起')
assert.match(browser, /<DisclosureBody className="dcu-wb-collection-body" open=\{ungroupedExpanded\}>/, '未分组项目必须复用统一折叠动画')
assert.doesNotMatch(browser, /dcu-wb-ungrouped-head/, '未分组不得保留与其他二级分类不一致的专用标题样式')
assert.match(browser, /assignWorkspaceToGroup\(current, dragged, groupId\)/, '拖入任意分组区域必须将项目归入该分组')
assert.match(browser, /className=\{`dcu-wb-collection[^`]*`\} key=\{group\.id\} onDragOver=/, '分组空白区域必须在冒泡阶段接收项目，不能抢占成员的精确落点')
assert.doesNotMatch(browser, /className="dcu-wb-collection" key=\{group\.id\} onDragOverCapture=/, '分组外层不得在捕获阶段接管全部项目拖拽')
assert.match(browser, /data-dcu-group-member[\s\S]*placeWorkspaceInGroup\(current, dragged, groupId, beforeId\)/, '跨分组拖到具体项目时必须同时更新归属和精确顺序')
assert.doesNotMatch(browser, /data-dcu-group-member[^\n]*onDragOverCapture=\{\(event\) => \{ if \(workspaceDragId === undefined\) return/, '分组成员精确落点不得只依赖 React 拖拽状态')
assert.match(browser, /className=\{`dcu-wb-ungrouped[^`]*`\} onDragOver=/, '未分组空白区域必须在冒泡阶段接收项目')
assert.doesNotMatch(browser, /className=\{`dcu-wb-ungrouped[^`]*`\} onDragOverCapture=/, '未分组外层不得在捕获阶段接管全部项目拖拽')
assert.match(browser, /data-dcu-ungrouped-member/, '未分组内的具体项目必须提供精确排序落点')
assert.doesNotMatch(browser, /data-dcu-ungrouped-member[^\n]*onDragOverCapture=\{\(event\) => \{ if \(workspaceDragId === undefined\) return/, '未分组成员精确落点不得只依赖 React 拖拽状态')
assert.match(browser, /setWorkspaceDropTarget\(\{ zone: 'ungrouped', ontoSection: true \}\)/, '未分组标题或空白区域必须接收项目拖拽')
assert.match(browser, /assignWorkspaceToGroup\(current, dragged\)/, '放入未分组区域必须移除项目的分组归属')
assert.match(browser, /sameWorkspaceDropTarget\(workspaceDropTargetRef\.current, target\)/, '重复的拖拽目标不得触发重复渲染')
assert.match(browser, /moveWorkspaceGroupMember\(current, dragged, groupId, beforeId\)/, '同一分组内拖动项目必须调整分组内顺序')
assert.doesNotMatch(browser, /sourceGroupId !== groupId\) return/, '具体项目落点不得拒绝未分组或其他分组的项目')
assert.doesNotMatch(browser, /aria-label=\{t\('workspace\.addToGroup', \{ name: group\.title \}\)\}/, '分组标题不应提供添加项目快捷按钮')
assert.doesNotMatch(browser, /aria-label=\{t\('workspace\.deleteGroup', \{ name: group\.title \}\)\}/, '分组标题不应提供删除分组快捷按钮')
assert.doesNotMatch(browser, /\.dcu-wb-collection\{[^}]*background:/, '分组容器不应使用常驻卡片背景')
assert.match(browser, /setMoveWorkspaceId\(workspaceId\)/, '项目菜单必须提供非拖拽的移动分组入口')
assert.match(browser, /assignWorkspaceToGroup\(current, workspaceId, groupId\)/, '移动到分组必须更新独立分组归属')
assert.match(browser, /moveWorkspaceToGroup\(\)/, '项目必须能退回未分组')
assert.match(browser, /const moveWorkspaceToGroup = \(groupId\?: string\): void =>[\s\S]*setPinnedWorkspaceIds\(ids => ids\.filter\(id => id !== workspaceId\)\)/, '通过菜单移动置顶项目时必须同步取消置顶')
assert.match(locales, /'workspace\.moveToGroupDescription': '选择项目所属分组；置顶项目移动后会取消置顶。'/, '移动分组说明必须明确置顶项目会取消置顶')
assert.match(browser, /deleteWorkspaceGroup\(current, deleteGroupId\)/, '删除分组必须仅解除归属')
assert.match(browser, /submitCreateGroup/, '新建分组必须支持键盘提交')
assert.match(browser, /<Modal open=\{createGroupOpen\} onClose=\{\(\) => \{ setCreateGroupOpen\(false\); setGroupTitleDraft\(''\); setError\(undefined\) \}\}/, '关闭新建分组弹窗必须清理共享错误')
assert.match(browser, /setCreateGroupOpen\(false\); setGroupTitleDraft\(''\); setError\(undefined\)/, '取消新建分组必须清理共享错误')
assert.doesNotMatch(browser, /type MenuState = \{ id: string; type: 'workspace' \| 'session' \| 'group'/, '菜单状态不得保留未使用的分组类型')
assert.doesNotMatch(browser, /if \(dragged !== undefined\) \{[^\n]*if \(dragged === undefined\) return/, '项目放下处理不得保留不可达判断')
assert.match(locales, /'workspace\.projects': '项目'/, '侧栏必须沿用项目标题')
assert.match(locales, /'workspace\.empty': '暂无项目'/, '项目空态必须描述项目而不是会话')
assert.match(locales, /'workspace\.moveToGroup': '移动到分组'/, '分组操作必须提供中文文案')

console.log('✓ workspace group UI assertions passed')
