/** 启动独立承载页实验：费用插件原文件不做修改，所有 API 为隔离的空数据夹具。 */
import { createRequire } from 'node:module'
import { readFile } from 'node:fs/promises'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { createServer } from 'node:http'
const require = createRequire(import.meta.url)
const { build } = createRequire(require.resolve('tsx/package.json'))('esbuild')
const billingRoot = process.env.DCU_BILLING_PACKAGE ?? join(homedir(), '.dsh', 'profiles', 'web', 'node_modules', '@kenz1117', 'dsh-ui-usage-billing')
const plugin = await readFile(join(billingRoot, 'lib', 'client.js'))
const packageInfo = JSON.parse(await readFile(join(billingRoot, 'package.json'), 'utf8'))
const output = await build({ entryPoints: ['scripts/billing-frame-preview.tsx'], bundle: true, write: false, outdir: 'preview', format: 'iife', platform: 'browser', jsx: 'automatic', loader: { '.css': 'local-css', '.woff': 'dataurl', '.woff2': 'dataurl', '.ttf': 'dataurl' }, define: { 'process.env.NODE_ENV': '"development"' } })
const js = output.outputFiles.find(file => file.path.endsWith('.js')).contents
const css = output.outputFiles.find(file => file.path.endsWith('.css'))?.contents ?? ''
const surface = `:root{font-family:system-ui,sans-serif;color-scheme:light;--dsw-alias-bg-base:#fff;--dsw-alias-bg-layer-1:#fff;--dsw-alias-bg-layer-2:#f5f5f5;--dsw-alias-bg-layer-3:#eee;--dsw-alias-label-primary:#262626;--dsw-alias-label-secondary:#666;--dsw-alias-label-tertiary:#888;--dsw-alias-label-caption:#888;--dsw-alias-border-l1:#ddd;--dsw-alias-border-l2:#ddd;--dsw-alias-interactive-bg-hover:#eee;--dsw-static-blue-500:#368af5}body[data-ds-dark-theme]{color-scheme:dark;--dsw-alias-bg-base:#181818;--dsw-alias-bg-layer-1:#181818;--dsw-alias-bg-layer-2:#242424;--dsw-alias-bg-layer-3:#303030;--dsw-alias-label-primary:#ddd;--dsw-alias-label-secondary:#aaa;--dsw-alias-label-tertiary:#888;--dsw-alias-label-caption:#888;--dsw-alias-border-l1:#363636;--dsw-alias-border-l2:#363636;--dsw-alias-interactive-bg-hover:#303030}html,body{margin:0;width:100%;height:100%;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary)}*{box-sizing:border-box}`
const embed = `#billing-root{display:none}.dsh-billing-modal{position:fixed!important;inset:0!important;transform:none!important;width:100%!important;max-width:none!important;height:100%!important;max-height:none!important;margin:0!important;border:0!important;border-radius:0!important;box-shadow:none!important;animation:none!important;background:var(--dsw-alias-bg-base)!important}.dsh-billing-modal [data-testid="billing-dashboard"]{height:100%;max-height:none}.dsh-billing-modal [data-testid="billing-dashboard-head"] h2{display:none}.dsh-billing-modal [data-testid="billing-dashboard"]>div:nth-last-child(2){min-height:0;flex:1}div[role=presentation]:has(>.dsh-billing-modal)>div[aria-hidden=true]:first-child{display:none!important}`
const frame = `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><link rel="stylesheet" href="/frame.css"><style>${surface}${embed}</style><body data-ds-dark-theme><div id="billing-root"></div><script src="/frame.js"></script><script src="/billing-plugin.js"></script></body></html>`
const main = `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>使用统计 · iframe 承载验证</title><style>${surface}body{display:grid;grid-template-columns:240px minmax(0,1fr)}nav{padding:20px 8px;background:#202322}button{font:inherit;color:inherit;background:transparent;border:0;padding:8px;cursor:pointer}nav button{width:100%;text-align:left;border-radius:10px}.active{background:#303432}main{display:flex;flex-direction:column;min-width:0;height:100vh;padding:28px 32px 0}header{display:flex;align-items:center;justify-content:space-between}h1{font-size:24px;font-weight:500;margin:0}p{font-size:12px;color:#929292;margin:12px 0 20px}iframe{width:100%;flex:1;min-height:0;border:0}#closed{display:none;padding:32px}</style><body data-ds-dark-theme><nav><button onclick="closePanel()">← 返回应用</button><p>记录与应用</p><button class="active" onclick="openPanel()">使用统计</button></nav><main><header><h1>使用统计</h1><button onclick="toggleTheme()">切换深浅主题</button></header><p>承载验证：加载费用插件原面板，当前为空数据，未连接或修改真实账单。</p><iframe title="费用插件原面板" src="/billing-frame"></iframe><div id="closed">已退出费用面板。<button onclick="openPanel()">重新打开</button></div></main><script>const frame=document.querySelector('iframe');let dark=true;function syncTheme(){frame.contentWindow.postMessage({type:'dcu-billing-theme',dark},location.origin)}function toggleTheme(){dark=!dark;document.body.toggleAttribute('data-ds-dark-theme',dark);syncTheme()}function closePanel(){frame.style.display='none';frame.src='about:blank';document.getElementById('closed').style.display='block'}function openPanel(){frame.style.display='block';frame.src='/billing-frame';document.getElementById('closed').style.display='none'}frame.addEventListener('load',syncTheme);window.addEventListener('message',event=>{if(event.origin===location.origin&&event.source===frame.contentWindow&&event.data?.type==='dcu-billing-close')closePanel()})</script></body></html>`
const zero = { calls: 0, input: 0, output: 0, cacheHit: 0, cacheMiss: 0, cost: 0, reasoning: 0 }
const fixtures = { '/api/billing/usage-stats': { total: zero, byModel: {}, byDay: {}, byDayModels: {} }, '/api/billing/balance': { balances: [] }, '/api/billing/subscriptions': { quotas: [] }, '/api/billing/relay-quotas': { quotas: [] }, '/api/billing/usage-tool': { enabled: false }, '/api/billing/pricing': {} }
const server = createServer((req, res) => {
  res.setHeader('Cache-Control', 'no-store')
  res.setHeader('Content-Security-Policy', "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self'; frame-src 'self'; frame-ancestors 'self'")
  if (req.method !== 'GET') { res.writeHead(405); res.end('预览不写入配置'); return }
  const path = new URL(req.url, 'http://127.0.0.1').pathname
  if (path in fixtures) { res.setHeader('Content-Type', 'application/json'); res.end(JSON.stringify(fixtures[path])); return }
  const asset = { '/': ['text/html; charset=utf-8', main], '/billing-frame': ['text/html; charset=utf-8', frame], '/frame.js': ['text/javascript', js], '/frame.css': ['text/css', css], '/billing-plugin.js': ['text/javascript', plugin] }[path]
  if (!asset) { res.writeHead(404); res.end(); return }
  res.setHeader('Content-Type', asset[0]); res.end(asset[1])
})
server.listen(Number(process.env.DCU_BILLING_PREVIEW_PORT ?? 4319), '127.0.0.1', () => console.log(`费用原组件 ${packageInfo.version} · iframe 验证：http://127.0.0.1:${server.address().port}/`))
